@base_url = http://localhost:5077/api

# LIVROS ######################################

### Criação de um novo livro
POST {{base_url}}/livros/cadastrar
Content-Type: application/json

{
    "Titulo" : "Prova de fogo",
    "Autor" : "matheus",
    "AnoPublicacao" : 2010,
    "Genero" : "romance",
    "ExemplaresDisponiveis" : 2
}

### Obtenção de todos os livros
GET {{base_url}}/livros/listar

### Busca de um livro pelo título
GET {{base_url}}/livros/buscar/Elon Musk

### Atualização de um livro
PUT {{base_url}}/livros/alterar/d946bf27-3d01-42db-9d84-d23446461f71
Content-Type: application/json

{
    "Titulo" : "Prova de fogo - Edição Revisada",
    "Autor" : "matheus",
    "AnoPublicacao" : 2010,
    "Genero" : "romance",
    "ExemplaresDisponiveis" : 3
}

### Deleção de um livro
DELETE {{base_url}}/livros/deletar/{id}

# USUARIOS ############################################

### Criação de um novo usuário
POST {{base_url}}/usuario/cadastrar
Content-Type: application/json

{
    "Nome" : "Pedro",
    "Telefone" : "133456789",
    "Email": "pedro@pedro"
}

### Obtenção de todos os usuários
GET {{base_url}}/usuario/listar

### Busca de um usuário pelo id
GET {{base_url}}/usuario/buscar/11699ee4-b148-4aef-b02e-7ddb1e74e4de

### Deleção de um usuário
DELETE {{base_url}}/usuario/deletar/{id}

# EMPRESTIMO #####################################

### Criação de um novo empréstimo
POST {{base_url}}/emprestimo/cadastrar
Content-Type: application/json

{
    "LivroId" : "0106fad7-3e7d-4e9b-aa95-05942d027559",
    "UsuarioId" : "a95d9341-a981-4fa5-b935-a79d79a0c209"
}

### Obtenção de todos os empréstimos
GET {{base_url}}/emprestimo/listar

# DEVOLUCAO #####################################

### Criação de uma nova devolução
POST {{base_url}}/devolucao/cadastrar
Content-Type: application/json

{
    "LivroId" : "0106fad7-3e7d-4e9b-aa95-05942d027559",
    "UsuarioId" : "a95d9341-a981-4fa5-b935-a79d79a0c209"
}

### Obtenção de todas as devoluções
GET {{base_url}}/devolucao/listar

### Alterar usuario
PUT {{base_url}}/usuario/alterar/1e89757e-9c64-472d-89dc-a695c76b1d43
Content-Type: application/json

{
    "Nome" : "Pedro",
    "Telefone" : "133456789",
    "Email": "pedro@pedro"
}
