@base_url = http://localhost:5077/api

# LIVROS ######################################

### Criação de um novo livro
POST {{base_url}}/livros/cadastrar
Content-Type: application/json

{
    "Titulo" : "Prova de fogo",
    "Autor" : "matheus",
    "AnoPublicacao" : 2010,
    "Genero" : "romance",
    "ExemplaresDisponiveis" : 2
}

### Obtenção de todos os livros
GET {{base_url}}/livros/listar

### Busca de um livro pelo título
GET {{base_url}}/livros/buscar/43a74312-bbf0-4b6e-980d-10b3d4be2a90

### Atualização de um livro
PUT {{base_url}}/livros/alterar/{id}
Content-Type: application/json

{
    "Titulo" : "Prova de fogo - Edição Revisada",
    "Autor" : "matus",
    "AnoPublicacao" : 2010,
    "Genero" : "romance",
    "ExemplaresDisponiveis" : 3
}

### Deleção de um livro
DELETE {{base_url}}/livros/deletar/{id}

# USUARIOS ############################################

### Criação de um novo usuário
POST {{base_url}}/usuario/cadastrar
Content-Type: application/json

{
    "Nome" : "Pedro",
    "Telefone" : "133456789",
    "Email": "pedro@pedro"
}

### Obtenção de todos os usuários
GET {{base_url}}/usuario/listar

### Busca de um usuário pelo nome
GET {{base_url}}/usuario/buscar/Pedro

### Deleção de um usuário
DELETE {{base_url}}/usuario/deletar/{id}

# EMPRESTIMO #####################################

### Criação de um novo empréstimo
POST {{base_url}}/emprestimo/cadastrar/0106fad7-3e7d-4e9b-aa95-05942d027559	
Content-Type: application/json

{
    "LivroId" : "0106fad7-3e7d-4e9b-aa95-05942d027559",
    "UsuarioId" : "a95d9341-a981-4fa5-b935-a79d79a0c209"
}

### Obtenção de todos os empréstimos
GET {{base_url}}/emprestimo/listar

# DEVOLUCAO #####################################

### Criação de uma nova devolução
POST {{base_url}}/devolucao/cadastrar
Content-Type: application/json

{
    "LivroId" : "43a74312-bbf0-4b6e-980d-10b3d4be2a90",
    "UsuarioId" : "a37f58e8-9ddb-4b50-b396-9ac6b70a1baf"
}

### Obtenção de todas as devoluções
GET {{base_url}}/devolucao/listar

