@base_url = http://localhost:5077/api

# LIVROS ######################################

### Criação de um novo livro
POST {{base_url}}/livros/cadastrar
Content-Type: application/json

{
    "Titulo" : "Prova de fogo",
    "Autor" : "matheus",
    "AnoPublicacao" : 2010,
    "Genero" : "romance",
    "ExemplaresDisponiveis" : 2
}

### Obtenção de todos os livros
GET {{base_url}}/livros/listar

### Busca de um livro pelo título
GET {{base_url}}/livros/buscar/Prova de fogo

### Atualização de um livro
PUT {{base_url}}/livros/alterar/{id}
Content-Type: application/json

{
    "Titulo" : "Prova de fogo - Edição Revisada",
    "Autor" : "matus",
    "AnoPublicacao" : 2010,
    "Genero" : "romance",
    "ExemplaresDisponiveis" : 3
}

### Deleção de um livro
DELETE {{base_url}}/livros/deletar/{id}

# USUARIOS ############################################

### Criação de um novo usuário
POST {{base_url}}/usuario/cadastrar
Content-Type: application/json

{
    "Nome" : "Pedro",
    "Telefone" : "133456789"
}

### Obtenção de todos os usuários
GET {{base_url}}/usuario/listar

### Busca de um usuário pelo nome
GET {{base_url}}/usuario/buscar/João

### Deleção de um usuário
DELETE {{base_url}}/usuario/deletar/{id}

# EMPRESTIMO #####################################

### Criação de um novo empréstimo
POST {{base_url}}/emprestimo/cadastrar
Content-Type: application/json

{
    "LivroId" : "b0655a85-0436-4249-8188-5016c13a3a83",
    "UsuarioId" : "8427c052-2423-446a-a089-7b664b7e7fa5"
}

### Obtenção de todos os empréstimos
GET {{base_url}}/emprestimo/listar

# DEVOLUCAO #####################################

### Criação de uma nova devolução
POST {{base_url}}/devolucao/cadastrar
Content-Type: application/json

{
    "LivroId" : "b0655a85-0436-4249-8188-5016c13a3a83",
    "UsuarioId" : "8427c052-2423-446a-a089-7b664b7e7fa5"
}

### Obtenção de todas as devoluções
GET {{base_url}}/devolucao/listar

### Obtenção de todas os empréstimos

GET {{base_url}}/emprestimo/listar